# Generated by Django 4.0.3 on 2022-04-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('door', models.CharField(max_length=50)),
                ('energy', models.CharField(max_length=50)),
                ('air_conditionner', models.BooleanField(default=False)),
                ('picture', models.ImageField(max_length=50, upload_to='')),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birthday', models.DateTimeField(auto_now_add=True, null=True)),
                ('sexe', models.CharField(max_length=50)),
                ('credible', models.BooleanField(default=False)),
                ('tel', models.CharField(max_length=50)),
                ('cni_num', models.CharField(max_length=50)),
                ('dlicense_num', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.CharField(max_length=50)),
                ('begin_hour', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('end_hour', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentmodule.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentmodule.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentmodule.reservation')),
            ],
        ),
    ]
