# Generated by Django 4.0.3 on 2022-04-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('color', models.CharField(max_length=100)),
                ('door', models.CharField(max_length=2)),
                ('emergy', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=100)),
                ('Year', models.DateField(blank=True)),
                ('description', models.CharField(max_length=30)),
                ('air_conditionner', models.BooleanField(default=False)),
                ('availaible', models.BooleanField(default=True)),
            ],
        ),
    ]
