# Generated by Django 4.0.3 on 2022-04-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimages',
            old_name='product',
            new_name='car',
        ),
    ]
