# Generated by Django 4.0.3 on 2022-04-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='modele',
            field=models.CharField(default='', max_length=50),
        ),
    ]
