# Generated by Django 4.0.3 on 2022-04-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0002_alter_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='emergy',
            new_name='energy',
        ),
    ]
