# Generated by Django 4.0.3 on 2022-05-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0002_car_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
