# Generated by Django 4.0.3 on 2022-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0002_rename_product_carimages_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='image',
            field=models.ImageField(upload_to='car_images/'),
        ),
    ]
