# Generated by Django 4.0.3 on 2022-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0003_rename_emergy_car_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
