# Generated by Django 4.0.3 on 2022-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0004_car_price_reservation_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('En cours', 'En cours'), ('Réservé', 'Réservé'), ("Hors d'état", "Hors d'état")], default='Nouveau', max_length=25),
        ),
    ]
