# Generated by Django 4.0.3 on 2022-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0005_alter_car_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
