# Generated by Django 4.0.3 on 2022-04-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0006_alter_car_options_car_slug_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminée', 'Terminée')], default='En attente', max_length=25),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Réservé', 'Réservé'), ('En réparation', 'En réparation')], default='Libre', max_length=25),
        ),
    ]
