# Generated by Django 4.0.3 on 2022-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0006_car_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(to='rentmodule.category'),
        ),
    ]
